baseline: Your blogging assistant
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
description: "The personal website of reedjones "
date:
  format: j F Y
  timezone: "United States/Los Angeles "
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Data&Art&Music&Code
baseurl: /
canonicalurl: true
